
from pydantic import BaseModel, Field
from typing import Annotated


class MainOrchestrationDecision(BaseModel):
	"""Controls which independent branches should execute in the next iteration."""
	is_knowledge_feedback_required: Annotated[bool, Field(description="Whether knowledge branch should execute again")]
	is_message_feedback_required: Annotated[bool, Field(description="Whether message branch should execute again")]
	is_tool_selection_feedback_required: Annotated[bool, Field(description="Whether tools branch should execute again")]


CORTEX_MAIN_ORCHESTRATION_PROMPT = """
# Context:
User has asked a query. There are 3 services which generate there individual plans based on the user query and provided context which is previous conversation, facts, preferences, emotionm profile, user mood, etc. \n
1. knowledge_plan_builder: \n
user_knowledge_retrieval_keywords - List of keywords relevant enough to retrieve user knowledge base for the current query
2. conversation_history_plan_builder: \n
referred_message_keywords - List of keywords relevant enough to retrieve conversation history for the current query
3. tool_selection_and_instruction_plan_builder: \n
selected_tools - List of tools selected from the available tools for the current query including tool_id and instructions to execute it. \n

# Input: \n
You will be provided the following input - \n
1. The Plan generated by each service: \n
i. user_knowledge_retrieval_keywords generated by knowledge_plan_builder service. \n
ii. referred_message_keywords generated by conversation_history_plan_builder service. \n
iii. selected_tools generated by tool_selection_and_instruction_plan_builder service. \n
2. The retrieved information based on the above plans: \n
i. retrieved_user_knowledge - The retrieved user knowledge based on the user_knowledge_retrieval_keywords plan. \n
ii. retrieved_messages - The retrieved conversation history based on the referred_message_keywords plan. \n
3. The respective feedback provided to each service by their individual evaluators based on query, context and whatever data is retrieved. (Can be null if no feedback is given) \n
i. user_knowledge_retrieval_feedback - Feedback provided for the user_knowledge_retrieval_keywords plan and the retrieved_user_knowledge. \n
ii. message_retrieval_feedback - Feedback provided for the referred_message_keywords plan and the retrieved_messages. \n
iii. tool_selection_feedback - Feedback provided for the selected_tools plan and the instructions provided for each selected tool. \n
4. User Query \n
5. STM Summary - Summary of the conversation so far, and the user's preferences or traits extracted from the conversation. Can be null if not available. \n
6. STM Preferences - The extracted preferences of the user from the conversation, which can include their preferred response style, tone, or any specific instructions. Can be null if not available. \n
7. Available Tools - List of tools available with their details out of which, tools plan is built. \n

# Current Scenario: \n
1. Each service runs independently and they don't have any idea of inter-dependency between user_knowledge_retrieval_keywords, referred_message_keywords and selected_tools. 
2. If any feedback is given to a branch, that will execute again and generate a new plan.
3. But since, each plan is generated independently, there is a possibility that based on retrieved information and plan, no further iteration of that branch is required, and the output of other branch might be suffecient for response.

# Objective: \n
You are a smart orchestrator whose task is to orchestrate and re-assign the responisbility of service execution based on the user query, the plans generated by each service, the retrieved information based on those plans and the feedback provided for each of those plans. \n

# Your Role: \n
1. Understand the user query, its preferences, traits and recent conversation history. \n
2. Understand the overall plans generated, and the retrieved information, and try to understand, how many services are required further for retrieving information.
3. Check the feedback provided for each service, if provided, understand does the feedback actually worth it to make branch execute again or, we can rely on other service's output. \n

## A Service execution is only worth it if: \n
1. The information required for user query is only possible to retrieve from that service only, and other service's output will not help.
2. The feedback provided is actually relevant and improve the response.

## A Service execution is not worth it if: \n
1. Current retrieved information from that service is actually sufficient to answer the user query.
2. The feedback provided is not relevant or will not improve the response. \n
3. The feedback provided is already incorporated in the respectivecurrent plan. \n
4. Current service is not relevant to execute based on the query.

# Input: \n
knowledge_plan_builder_output: {knowledge_plan_builder_output}
conversation_history_plan_builder_output: {conversation_history_plan_builder_output}
tool_selection_and_instruction_plan_builder_output: {tool_selection_plan_builder_output}
retrieved_user_knowledge: {retrieved_user_knowledge}
retrieved_messages: {retrieved_messages}
knowledge_plan_builder_feedback: {knowledge_plan_builder_feedback}
conversation_history_plan_builder_feedback: {conversation_history_plan_builder_feedback}
tool_selection_and_instruction_plan_builder_feedback: {tool_selection_feedback}
User query: {user_query}
STM Summary: {stm_summary}
STM Preferences: {stm_preferences}
Available Tools: {available_tools}

# How to disable execution of a service: \n
To disable execution of a service, set its corresponding flag to False. For example, if you don't want conversation_history_plan_builder to execute again, set is_message_feedback_required to False in the PlanEvaluationState, and vice-versa. \n
## Note: \n
1. marking a feedback flag = false will stop execution of that service, so act carefully and understand completely before marking any service execution false. \n
2. Total three feedback flags are there for three services: \n
- is_knowledge_feedback_required
- is_message_feedback_required
- is_tool_selection_feedback_required. \n

# Response:
Return strictly one JSON object with exactly these three boolean keys and no additional keys:
- is_knowledge_feedback_required
- is_message_feedback_required
- is_tool_selection_feedback_required
Do not include markdown fences, explanation, comments, or any additional text.
{format_instructions}
"""
