from pydantic import BaseModel, Field
from typing import Annotated


class MainOrchestrationDecision(BaseModel):
    """Controls which independent branches should execute in the next iteration."""
    reasoning: Annotated[str, Field(description="A detailed reasoning of why you have decided to stop or continue execution of each service based on the above provided information and feedback. Limit 120 words.")]
    is_knowledge_plan_refinement_required: Annotated[bool, Field(description="Whether the refinement of knowledge plan is required or not")]
    is_message_plan_refinement_required: Annotated[bool, Field(description="Whether the refinement of message plan is required or not")]
    is_tool_selection_plan_refinement_required: Annotated[bool, Field(description="Whether the refinement of tool selection plan is required or not")]

CORTEX_MAIN_ORCHESTRATION_PROMPT = """
# Input:
1. The Plan generated by each service. \n
2. The retrieved information based on the above plans: retrieved_user_knowledge and retrieved_messages. \n
3. The respective feedback provided to each service by their individual evaluators based on query, context and whatever data is retrieved. (Can be null if no feedback is given) \n
- user_knowledge_retrieval_feedback
- message_retrieval_feedback
- tool_selection_feedback
4. User Query \n
5. STM Summary - Summary of the conversation so far, and the user's preferences or traits extracted from the conversation. Can be null if not available. \n
6. STM Preferences - The extracted preferences of the user from the conversation, which can include their preferred response style, tone, or any specific instructions. Can be null if not available. \n
7. Available Tools - List of tools available with their details out of which, tools plan is built. \n
8. Iteration Count - Number of times the planner-evaluator has iterated over the same query. \n

# Context:
User has asked a query. There are 3 services which runs independently and generate there individual plans. Each don't have any idea of inter-dependency between user_knowledge_retrieval_keywords, referred_message_keywords and selected_tools. \n
2. If any feedback is given to a branch, that will execute again and generate a new refined plan. \n
3. But since, each plan is generated independently, there is a possibility that based on retrieved information and plan, no further iteration of that branch is required, or the output of other branch might be suffecient for response. \n

### Individual Plans: \n
1. user_knowledge_retrieval_keywords - List of keywords relevant enough to retrieve user knowledge base for the current query.
2. referred_message_keywords - List of keywords relevant enough to retrieve conversation history for the current query.
3. selected_tools - List of tools selected from the available tools for the current query including tool_id and instructions to execute it. \n

# Objective: \n
a. You are a smart orchestrator whose task is decide the required services which needs to be executed to refine the plan, may be zero, one or more. \n
b. You have higher authority over planner and evaluator of each service during the decision. \n
c. You can use evaluator feedback for analysis, but never blindly follow it. You have to decide whether to rely on the feedback or not. \n

## A Refinement of "Service Plan" is worth it if: \n
1. The information required for user query is only possible to retrieve from that service only, and other service's output will not help.
2. The feedback provided is actually relevant and improve the response. \n

## A Service execution is not worth it and must be stopped if: \n
1. Current retrieved information from that service is actually sufficient to answer the user query. \n
2. The feedback provided is not relevant or will not improve the response. \n
3. The feedback provided is already incorporated in the respective current plan. \n
4. Current service was not required to execute at all based on the query and must be stopped. \n
5. If after multiple iterations, the plan is not improving at all, which might be due to no data present at all. \n
6. Even if evaluator feedback for one service is helpful, but you think that information from other service is sufficient to answer the query, then you can stop that service as well to reduce unnecessary iterations. \n

# Input: \n
knowledge_plan_builder_output: {knowledge_plan_builder_output}
conversation_history_plan_builder_output: {conversation_history_plan_builder_output}
tool_selection_and_instruction_plan_builder_output: {tool_selection_plan_builder_output}
retrieved_user_knowledge: {retrieved_user_knowledge}
retrieved_messages: {retrieved_messages}
knowledge_plan_builder_feedback: {knowledge_plan_builder_feedback}
conversation_history_plan_builder_feedback: {conversation_history_plan_builder_feedback}
tool_selection_and_instruction_plan_builder_feedback: {tool_selection_feedback}
User query: {user_query}
STM Summary: {stm_summary}
STM Preferences: {stm_preferences}
Available Tools: {available_tools}
Iteration Count: {iteration_count}

# How to control execution: \n
Total three flags are there for three services: \n
- is_knowledge_plan_refinement_required
- is_message_plan_refinement_required
- is_tool_selection_plan_refinement_required

## Impact on each service execution: \n
a. If marked false, no further refinement of the plan will be done and no new data is fetched. In case of: 
i. knowledge_plan and messages - already fetched data (if any) will be used.
ii. tool selection - already selected tools (if any) will be executed. \n
c. If marked true, plan will be refined and new data will be fetched based on the refined plan. \n

# Note: \n
1. Marking a service refinement false will stop only its further refinement, but execution will continue.
2. You have to decide flags based on refinement of the plan required or not, and not based on the execution of the plan. \n

# Response:
Strictly respond in the mentioned format. Do not include any text, markdown fences, explanation, comments, etc. \n
{format_instructions}
"""
