services:
  pg:
    image: pgvector/pgvector:pg17
    container_name: cortex-pg-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cortex_postgres_db
      POSTGRES_DB: cortex-assistant-db
    ports:
      - "5460:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./cortex_cm/pg/sql/create_tables.sql:/docker-entrypoint-initdb.d/10-create_tables.sql

  redis:
    image: redis:latest
    container_name: cortex-redis-db
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data

  cortex-queue:
    build: .
    container_name: cortex-queue
    restart: always
    ports:
      - "8001:8001"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_URL=postgresql://postgres:cortex_postgres_db@pg:5432/cortex-assistant-db
      - EVENT_TOOL_URL=http://cortex-event-tool:8002
    command: python cortex_queue/main.py
    depends_on:
      - redis
      - pg

  cortex-server:
    build: .
    container_name: cortex-server
    restart: always
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_URL=postgresql://postgres:cortex_postgres_db@pg:5432/cortex-assistant-db
      - CORTEX_QUEUE_URL=http://cortex-queue:8001
      - EVENT_TOOL_URL=http://cortex-event-tool:8002
      - USE_REMOTE_QUEUE=true
    command: python cortex_server/main.py
    depends_on:
      - redis
      - pg
      - cortex-queue

  cortex-core:
    build: .
    container_name: cortex-core
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_URL=postgresql://postgres:cortex_postgres_db@pg:5432/cortex-assistant-db
      - CORTEX_QUEUE_URL=http://cortex-queue:8001
      - EVENT_TOOL_URL=http://cortex-event-tool:8002
      - USE_REMOTE_QUEUE=true
    command: python cortex_core/worker.py
    depends_on:
      - redis
      - pg
      - cortex-queue

  cortex-event-tool:
    build: .
    container_name: cortex-event-tool
    restart: always
    ports:
      - "8002:8002"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_URL=postgresql://postgres:cortex_postgres_db@pg:5432/cortex-assistant-db
      - CORTEX_QUEUE_URL=http://cortex-queue:8001
    command: python cortex_event_tool/req.py
    depends_on:
      - redis
      - pg
      - cortex-queue

  cortex-event-worker:
    build: .
    container_name: cortex-event-worker
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_URL=postgresql://postgres:cortex_postgres_db@pg:5432/cortex-assistant-db
      - CORTEX_QUEUE_URL=http://cortex-queue:8001
    command: python cortex_event_tool/worker.py
    depends_on:
      - redis
      - pg
      - cortex-queue
      - cortex-event-tool
