services:
  db:
    image: pgvector/pgvector:pg17
    container_name: cortex-assistant-db-server
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cortex_postgres_db
      POSTGRES_DB: cortex-assistant-db
    ports:
      - "5460:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: cortex-assistant-redis-server
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data