from pydantic import BaseModel, Field
from typing import Annotated, Optional
from cortex.graph.state import ConversationState, OrchestrationState

class InternalFeedbackKnowledge(BaseModel):
    is_feedback_required: Annotated[bool, Field(description="Whether feedback is required for the current response or not")]
    user_knowledge_retrieval_feedback: Annotated[Optional[str], Field(description="Feedback on the user knowledge retrieval part of the plan")] = None

class InternalFeedbackMessages(BaseModel):
    is_feedback_required: Annotated[bool, Field(description="Whether feedback is required for the current response or not")]
    message_retrieval_feedback: Annotated[Optional[str], Field(description="Feedback on the message retrieval part of the plan")] = None

class InternalFeedbackTools(BaseModel):
    is_feedback_required: Annotated[bool, Field(description="Whether feedback is required for the current response or not")]
    tool_selection_feedback: Annotated[Optional[str], Field(description="Feedback on the tool selection part of the plan")] = None

CORTEX_MAIN_KNOWLEDGE_EVALUATION_PROMPT = """
# Context:
For a given user query, the orchestrator has generated a plan. The plan includes the following: \n
1. user_knowledge_retrieval_keywords - It contains a list of strings where each string is relevant enough to fetch a specific piece of user knowledge. Each string semantic meaning is different from the others. \n
2. user_knowledge_acceptance_threshold - A float between 0.2 and 0.6 representing the similarity threshold for accepting user knowledge items retrieved based on the keywords. \n

# Objective:
You are a smart evaluator, whose job is to evaluate the above plan generated by the Orchestrator based on the user query and the context provided, and provide the relevant feedback.\n

# Input Format:
1. User Query \n
2. Orchestration Plan
3. Retrieved User Knowledge - The relevant user knowledge retrieved from the database based on the user_knowledge_retrieval_keywords and respective user_knowledge_acceptance_threshold provided by the Orchestrator. \n
4. List of previous feedbacks provided by you for the same query (if any in past).
5. User current Mood (from the query) (can be happy, sad, angry, etc.) \n
6. User's previous emotional profile (if any else null) -
    a. Emotional Level (1-10) - Intensity of user emotions at that point of time and how much they prefer emotional responses \n
    b. Logical Level (1-10) - How logically the user thinks and prefers logical discussions. \n
    c. Social Level (1-10) - How socially active the user is and how much they are influenced by their social interactions.
    d. Context Summary - The respective pattern, preferences and behavior summary of the user for that particular combination of mood and time of the day. \n

# Input: \n
User Query: {user_query}
Orchestration Plan: {orchestration_plan}
Retrieved User Knowledge: {retrieved_user_knowledge}
Previous Feedbacks: {previous_feedback}
User Mood: {user_mood}
User Previous Emotional Profile: {user_emotional_profile}

# What to evaluate: \n
a. Understand the user query, the retrieved user knowledge, and the respective retrieval plan provided by the Orchestrator. \n
b. Take into account the user's emotional state, preferences, and the previous feedbacks provided by you for the same query (if any). \n
c. Based on it, check \n
i. whether the current retrieved User Knowledge is relevant and sufficient for generating the response. \n
ii. whether the rerieved information is relevant but insufficient, or relevant but there is some irrelevant information as well. \n

## Give feedback in following cases: \n
i. No information is retrieved. \n
ii. Retrieved information is not relevant to the user query or the context. \n
iii. Retrieved information is relevant but insufficient. \n
iv. Retrieved information is relevant but there is some irrelevant information as well. \n

## No feedback required in following cases: \n
i. If you think information is sufficient and dont need further improvement.
ii. If you have already given the same feedback in the previous evaluation.
iii. If orchestrator has already incorporated the previous feedback in the current plan. \n
iv. Do not generate "nice-to-have" or stylistic suggestions when retrieval is already relevant and sufficient. In such cases, `is_feedback_required` must be `False`. \n

# How to give feedback:
## If You have to provide specific feedback, you must mention what kind of knowledge is missing or irrelevant. It should include:  \n
i. Instructions to either add more specific keywords, remove previously selected keywords from user_knowledge_retrieval_keywords \n
ii. Value of new user_knowledge_acceptance_threshold if you think more or less knowledge items should be retrieved based on the current retrieval and the user query. \n
iii. Give straight feedback, never say, "Your information is relevant but insufficient", etc. Act blunt and just give specific insstructions in concise manner. \n

### How to decide the user_knowledge_acceptance_threshold:
- CORE RULE: Higher threshold means stricter filtering and fewer documents accepted. Lower threshold means broader filtering and more documents accepted. \n
- If no user knowledge is retrieved, you MUST recommend lowering threshold. \n
- If retrieved knowledge is relevant but insufficient, recommend lowering threshold and/or broadening keywords. \n
- Increase threshold ONLY when retrieval already returns sufficient information plus clearly irrelevant items, and stricter filtering is required. \n
- If retrieval is empty and you suggest increasing threshold, that is logically invalid and must be avoided. \n
- For general knowledge retrieval: use 0.25 to 0.40.
- For specific/strict knowledge: use 0.40 to 0.55.
- Do not suggest threshold above 0.55 unless the retrieved set is already large and noisy.

### set `is_feedback_required` to `True` in this case. \n

## If you don't have to provide any feedback, then 
i. keep the feedback empty or null and set `is_feedback_required` to `False`. \n

# Response:
After evaluating the plan, you have to provide the feedback strictly in the below mentioned format. Strictly follow format and never print any function, code, explanation, text, etc.
{format_instructions}
"""

CORTEX_MAIN_MESSAGE_EVALUATION_PROMPT = """
# Context:
For a given user query, the orchestrator has generated a plan. The plan includes the following: \n
1. is_message_referred - If true, referred_message_keywords are used to retrieve the relevant messages from the past conversation and are provided later. If false, then referred_message_keywords will be empty or null. \n
2. referred_message_keywords - The string of relevant keywords generated based on current query that will be used to fetch the messages from the past conversation done \n

# Objective:
You are a smart evaluator, whose job is to evaluate the above plan generated by the Orchestrator based on the user query and the context provided, and provide the relevant feedback.\n

# Input Format:
1. User Query \n
2. Orchestration Plan
3. Retrieved Messages - The relevant messages retrieved from the message history based on the message retrieval plan provided by the Orchestrator. (If is_message_referred is true else null) \n
4. List of previous feedbacks provided by you for the same query (if any in past).
5. User current Mood (from the query) (can be happy, sad, angry, etc.) \n
6. User's Long term Memory - Relevant facts, preferences, traits and behavious of the user persisted based on past interactions. \n

# Input: \n
User Query: {user_query}
Orchestration Plan: {orchestration_plan}
Retrieved Messages: {retrieved_messages}
Previous Feedbacks: {previous_feedback}
User Mood: {user_mood}
User's Long term Memory: {retrieved_user_knowledge}

# What to evaluate: \n
a. Understand the user query, the retrieved messages, and the respective message retrieval plan provided by the Orchestrator. \n
b. Take into account the user's emotional state, preferences, long term memory and the previous feedbacks provided by you for the same query (if any). \n
c. Based on it, check \n
i. whether the current retrieved messages are relevant and sufficient for generating the response. \n
ii. whether the referred_message_keywords provided are relevant and sufficient based on user's query, preferences, facts and long-term memory. \n

## Give feedback in following cases: \n
i. check if number of keywords in referred_message_keywords are atleast 3, else suggest to increase it also.
ii. No messages are retrieved even when is_message_referred is true. \n
iii. Retrieved messages are not relevant to the user query or the context. \n
iv. Retrievd messages are sufficient but there is some irrelevant information as well. \n

## No feedback required in following cases: \n
i. If you think retrieved messages are sufficient and relevant and dont need further improvement.
ii. If you have already given the same feedback in the previous evaluation.
iii. If orchestrator has already incorporated the previous feedback in the current plan. \n
iv. Do not generate "nice-to-have" or stylistic suggestions when retrieval is already relevant and sufficient. In such cases, `is_feedback_required` must be `False`. \n
v. Do not request additional keyword tweaks just for optimization. Mark `is_feedback_required` as `False`. \n

# How to give feedback:
## If You have to provide specific feedback, then provide `is_feedback_required` as `True`, and you must mention: \n
i. What kind of messages are missing or irrelevant. It should include instructions to either add the reference, remove the reference or modify the referred_message_keywords for message retrieval. \n
ii. Also suggest relevant keywords or references to be added or removed from the referred_message_keywords for improving the message retrieval. \n
iii. Give straight feedback, never say, "Your information is relevant but insufficient", etc. Act blunt and just give specific insstructions in concise manner. \n

## If you don't have to provide any feedback, then 
i. keep the feedback empty or null and set `is_feedback_required` to `False`.

# Response:
After evaluating the plan, you have to provide the feedback strictly in the below mentioned format. Strictly follow format and never print any function, code, explanation, text, etc.
{format_instructions}
"""

CORTEX_MAIN_TOOL_EVALUATION_PROMPT = """
# Context:
For a given user query, the orchestrator has generated a plan. The plan includes the following: \n
1. is_tool_required - Whether any tool is required to process the user query or not
2. selected_tools - List of selected tools with their respective instructions for execution

# Objective:
You are a smart evaluator for tools, whose job is to evaluate the plan generated by the Orchestrator based on the user query and the context provided, and provide the relevant feedback.\n

# Input Format:
1. User Query \n
2. Orchestration Plan
3. List of previous feedbacks provided by you for the same query (if any in past).
4. User current Mood (from the query) (can be happy, sad, angry, etc.) \n
5. User's previous emotional profile (if any else null) -
    a. Emotional Level (1-10) - Intensity of user emotions at that point of time and how much they prefer emotional responses \n
    b. Logical Level (1-10) - How logically the user thinks and prefers logical discussions. \n
    c. Social Level (1-10) - How socially active the user is and how much they are influenced by their social interactions.
    d. Context Summary - The respective pattern, preferences and behavior summary of the user for that particular combination of mood and time of the day. \n
6. User's Long term Memory - Relevant facts, preferences, traits and behavious of the user persisted based on past interactions. \n
7. User's Relevant Conversation History - Relevant past conversation messages based on the user query (if any). \n

# Current context: \n
Tool is selected by the orchestrator and will be executed by the tool manager once approved by you. Tool executor has no information about user's preferences, likes or dislikes. Only orchestrator or you have this information.

# Input: \n
User Query: {user_query}
Orchestration Plan: {orchestration_plan}
Previous Feedbacks: {previous_feedback}
User Mood: {user_mood}
User Previous Emotional Profile: {user_emotional_profile}
User's Long term Memory: {retrieved_user_knowledge}
User's Relevant Conversation History: {retrieved_messages}

# What to evaluate: \n
a. Understand the user query, the selected tools and their instructions, and the respective tool selection plan provided by the Orchestrator. \n
b. Take into account the user's emotional state, preferences, long term memory, recent conversation history and the previous feedbacks provided by you for the same query (if any). \n
c. Based on it, check \n
i. whether the selected tools are relevant and sufficient for processing the user query. \n
ii. whether the respective tool instructions provided are relevant and sufficient based on user query, preferences, emotional profile, long-term memory and recent conversation history. \n

## Give feedback in following cases: \n
i. If any of the selected tool is actually not required. \n
ii. If a tool from the available tools list should be used as per the context but not selected by the orchestrator. \n
iii. If tool instructions for selected tools are not aligned with the user query, preferences, emotional profile, long-term memory or recent conversation history. \n
iv. If Tool instructions include things like "User's preference or user's favourite X or Y", you have to ask orchestrator to make it more specific, as tool executor has no information about user's preferences, likes or dislikes. \n 

## No feedback required in following cases: \n
i. If you think selected tools and their instructions are relevant and sufficient for processing the user query and dont need further improvement.
ii. If you have already given the same feedback in the previous evaluation.
iii. If orchestrator has already incorporated the previous feedback in the current plan. \n

# How to give feedback:
## If You have to provide specific feedback then provide `is_feedback_required` as `True`, and you must mention:
1. Provide specific feedback on what new tools should be selected or which tool should be removed.
2. What instructions should be provided for the tools to make them more effective and personalized for the user query. \n
3. For example, if instructions say "Search for user's favourite restaurants in the city", and long term memory say user like "x" restaurant, then you have to tell orchestrator mention about x in instructions as tool_executor has no idea about x.\n
4. Above is just an example, never copy anything from it in your feedback, only use it as a reference for how to ask for more specific instructions. \n
5. Give straight feedback, never say, "Your information is relevant but insufficient", etc. Act blunt and just give specific insstructions in concise manner. \n

## If you don't have to provide any feedback, then
1. keep the feedback empty or null and set `is_feedback_required` to `False`. \n
2. Do not generate "nice-to-have" or stylistic suggestions when selected tools and instructions are already relevant and sufficient.

### Available Tools:
{available_tools}

# Response:
After evaluating the plan, you have to provide the feedback strictly in the below mentioned format. Strictly follow format and never print any function, code, explanation, text, etc.
{format_instructions}
"""
