from pydantic import BaseModel, Field
from typing import Annotated, Optional
from cortex.graph.state import ConversationState, OrchestrationState

class InternalFeedbackKnowledge(BaseModel):
    is_feedback_required: Annotated[bool, Field(description="Whether feedback is required for the current response or not")]
    user_knowledge_retrieval_feedback: Annotated[Optional[str], Field(description="Feedback on the user knowledge retrieval part of the plan")] = None

class InternalFeedbackMessages(BaseModel):
    is_feedback_required: Annotated[bool, Field(description="Whether feedback is required for the current response or not")]
    message_retrieval_feedback: Annotated[Optional[str], Field(description="Feedback on the message retrieval part of the plan")] = None

class InternalFeedbackTools(BaseModel):
    is_feedback_required: Annotated[bool, Field(description="Whether feedback is required for the current response or not")]
    tool_selection_feedback: Annotated[Optional[str], Field(description="Feedback on the tool selection part of the plan")] = None

CORTEX_MAIN_KNOWLEDGE_EVALUATION_PROMPT = """
# Context:
For a given user query, the orchestrator has generated a plan. The plan includes the following: \n
1. user_knowledge_retrieval_keywords - It contains a list of strings where each string is relevant enough to fetch a specific piece of user knowledge. Each string semantic meaning is different from the others. \n
2. user_knowledge_acceptance_threshold - A float between 0.2 and 0.6 representing the similarity threshold for accepting user knowledge items retrieved based on the keywords. \n

# Objective:
You are a smart evaluator, whose job is to evaluate the above plan generated by the Orchestrator based on the user query and the context provided, and provide the relevant feedback.\n

# Input Format:
1. User Query \n
2. Orchestration Plan
3. Retrieved User Knowledge - The relevant user knowledge retrieved from the database based on the user_knowledge_retrieval_keywords and respective user_knowledge_acceptance_threshold provided by the Orchestrator. \n
4. List of previous feedbacks provided by you for the same query (if any in past).
5. User current Mood (from the query) (can be happy, sad, angry, etc.) \n
6. User's previous emotional profile (if any else null) -
    a. Emotional Level (1-10) - Intensity of user emotions at that point of time and how much they prefer emotional responses \n
    b. Logical Level (1-10) - How logically the user thinks and prefers logical discussions. \n
    c. Social Level (1-10) - How socially active the user is and how much they are influenced by their social interactions.
    d. Context Summary - The respective pattern, preferences and behavior summary of the user for that particular combination of mood and time of the day. \n

# Evaluation Instructions:
1. Evaluate the user query, the orchestration plan and the retrieved data based on the plan. \n
2. Also take into account the previous feedbacks provided by you for the same query (if any provided) and the user's emotional state and preferences. \n
3. Based on this, you have to evaluate and decide the feedback \n

# Input: \n
User Query: {user_query}
Orchestration Plan: {orchestration_plan}
Retrieved User Knowledge: {retrieved_user_knowledge}
Previous Feedbacks: {previous_feedback}
User Mood: {user_mood}
User Previous Emotional Profile: {user_emotional_profile}

# Feedback Instructions:
## USER KNOWLEDGE BASE \n
a. Check whether the current retrieved User Knowledge is relevant and sufficient for generating the response. \n
b. Give feedback in following cases: \n
i. No information is retrieved. \n
ii. Retrieved information is not relevant to the user query or the context. \n
iii. Retrieved information is relevant but insufficient. \n
iv. Retrieved information is relevant but there is some irrelevant information as well. \n
c. You have to provide specific feedback on what kind of knowledge is missing or irrelevant. It should include:  \n
i. Instructions to either add more specific keywords, remove previously selected keywords from user_knowledge_retrieval_keywords \n
ii. Value of new user_knowledge_acceptance_threshold if you think more or less knowledge items should be retrieved based on the current retrieval and the user query. \n

### user_knowledge_acceptance_threshold guidance:
- CORE RULE: Higher threshold means stricter filtering and fewer documents accepted. Lower threshold means broader filtering and more documents accepted. \n
- If no user knowledge is retrieved, you MUST recommend lowering threshold. \n
- If retrieved knowledge is relevant but insufficient, recommend lowering threshold and/or broadening keywords. \n
- Increase threshold ONLY when retrieval already returns sufficient information plus clearly irrelevant items, and stricter filtering is required. \n
- If retrieval is empty and you suggest increasing threshold, that is logically invalid and must be avoided. \n
- For general knowledge retrieval: use 0.25 to 0.40.
- For specific/strict knowledge: use 0.40 to 0.55.
- Do not suggest threshold above 0.55 unless the retrieved set is already large and noisy.
d. If information retrieved is relevant and sufficient, then keep the feedback empty or null. \n

# Strict Guidelines for Feedback:
1. If you have added any feedback, then provide `is_feedback_required` as `True`, else `False`. \n
2. Don't repeat the same feedback again and again in the future evaluations. \n

# Response:
After evaluating the plan, you have to provide the feedback strictly in the below mentioned format. Strictly follow format and never print any function, code, explanation, text, etc.
{format_instructions}
"""

CORTEX_MAIN_MESSAGE_EVALUATION_PROMPT = """
# Context:
For a given user query, the orchestrator has generated a plan. The plan includes the following: \n
1. is_message_referred - If true, referred_message_keywords are used to retrieve the relevant messages from the past conversation and are provided later. If false, then referred_message_keywords will be empty or null. \n
2. referred_message_keywords - The string of relevant keywords generated based on current query that will be used to fetch the messages from the past conversation done \n

# Objective:
You are a smart evaluator, whose job is to evaluate the above plan generated by the Orchestrator based on the user query and the context provided, and provide the relevant feedback.\n

# Input Format:
1. User Query \n
2. Orchestration Plan
3. Retrieved Messages - The relevant messages retrieved from the message history based on the message retrieval plan provided by the Orchestrator. (If is_message_referred is true else null) \n
4. List of previous feedbacks provided by you for the same query (if any in past).
5. User current Mood (from the query) (can be happy, sad, angry, etc.) \n
6. User's Long term Memory - Relevant facts, preferences, traits and behavious of the user persisted based on past interactions. \n

# Evaluation Instructions:
1. Evaluate the user query, the orchestration plan and the retrieved data based on the plan. \n
2. Also take into account the previous feedbacks provided by you for the same query (if any provided) and the user's preferences. \n
3. Based on this, you have to evaluate and decide the feedback \n

# Input: \n
User Query: {user_query}
Orchestration Plan: {orchestration_plan}
Retrieved Messages: {retrieved_messages}
Previous Feedbacks: {previous_feedback}
User Mood: {user_mood}
User's Long term Memory: {retrieved_user_knowledge}

# Feedback Instructions:
## MESSAGE RETRIEVAL \n
a. Check whether the current retrieved messages are relevant and sufficient for generating the response. \n
b. Check whether the referred_message_keywords provided are relevant and sufficient based on user's query, preferences, facts and long-term memory. \n
c. If not, then provide specific feedback on what kind of messages are missing or irrelevant. \n
d. It should include instructions to either add the reference, remove the reference or modify the referred_message_keywords for message retrieval. \n
e. Also suggest relevant keywords or references to be added or removed from the referred_message_keywords for improving the message retrieval. \n
f. Check whether number of keywords in referred_message_keywords are atleast 3, else suggest to increase it also.
g. If its relevant and sufficient, then keep it empty or null. \n

# Strict Guidelines for Feedback:
1. If you have added any feedback, then provide `is_feedback_required` as `True`, else `False`. \n
2. Don't repeat the same feedback again and again in the future evaluations. \n

# Response:
After evaluating the plan, you have to provide the feedback strictly in the below mentioned format. Strictly follow format and never print any function, code, explanation, text, etc.
{format_instructions}
"""

CORTEX_MAIN_TOOL_EVALUATION_PROMPT = """
# Context:
For a given user query, the orchestrator has generated a plan. The plan includes the following: \n
1. is_tool_required - Whether any tool is required to process the user query or not
2. selected_tools - List of selected tools with their respective instructions for execution

# Objective:
You are a smart evaluator for tools, whose job is to evaluate the plan generated by the Orchestrator based on the user query and the context provided, and provide the relevant feedback.\n

# Input Format:
1. User Query \n
2. Orchestration Plan
3. List of previous feedbacks provided by you for the same query (if any in past).
4. User current Mood (from the query) (can be happy, sad, angry, etc.) \n
5. User's previous emotional profile (if any else null) -
    a. Emotional Level (1-10) - Intensity of user emotions at that point of time and how much they prefer emotional responses \n
    b. Logical Level (1-10) - How logically the user thinks and prefers logical discussions. \n
    c. Social Level (1-10) - How socially active the user is and how much they are influenced by their social interactions.
    d. Context Summary - The respective pattern, preferences and behavior summary of the user for that particular combination of mood and time of the day. \n
6. User's Long term Memory - Relevant facts, preferences, traits and behavious of the user persisted based on past interactions. \n
7. User's Relevant Conversation History - Relevant past conversation messages based on the user query (if any). \n

# Evaluation Instructions:
1. Evaluate the user query, and the orchestration plan, and understand the user requirements, preferences, and context. \n
2. Also take into account the previous feedbacks provided by you for the same query (if any provided) and the user's emotional state and preferences. \n
3. Based on this, you have to evaluate and decide the feedback \n

# Input: \n
User Query: {user_query}
Orchestration Plan: {orchestration_plan}
Previous Feedbacks: {previous_feedback}
User Mood: {user_mood}
User Previous Emotional Profile: {user_emotional_profile}
User's Long term Memory: {retrieved_user_knowledge}
User's Relevant Conversation History: {retrieved_messages}

# Feedback Instructions:
## Tool Selection \n
Tool is selected by the orchestrator and will be executed by the tool manager once approved by you. \n
1. Check whether the selected tools are relevant and sufficient for processing the user query. \n
2. Also check the respective tool instructions (if any) based on the user query and context provided. \n
3. Give feedback if: \n
i. No tool is selected but you think some tool is required. \n
ii. Some tool is selected but it is not relevant or necessary for the query. \n
iii. The tool instructions provided are not sufficient or relevant to the user query and the context. \n
iv. Tool instructsions require modifications based on user query, user long term memory, user emotional profile, preferences, or recent conversation history. \n
4. Provide specific feedback on what tools should be selected or removed, and what instructions should be provided for the tools to make them more effective and personalized for the user query. \n
5. Strictly note that, tool executor has no information about user's preferences, likes or dislikes. So if Tool instructions include things like "User's preference or user's favourite X or Y", you have to ask planner to make it more specific. \n
6. You will be given available tools list and their functionalities as well, so you can refer to that while giving feedback/. \n
7. You can also refer user's preferences, emotional profile, long-term memory and recent conversation history while giving feedback. \n

### Available Tools:
{available_tools}

# Strict Guidelines for Feedback:
1. If you have added any feedback, then provide `is_feedback_required` as `True`, else `False`. \n
2. Don't repeat the same feedback again and again in the future evaluations. \n

# Response:
After evaluating the plan, you have to provide the feedback strictly in the below mentioned format. Strictly follow format and never print any function, code, explanation, text, etc.
{format_instructions}
"""
