import asyncio
from sensory.STT import STTClient
from sensory.TTS import TTSClient
from cortex.voice.model import VoiceMainModel
from utility.main import iterate_tokens_async
from nltk.tokenize import sent_tokenize
from typing import AsyncGenerator
from logger import logger
from cortex.main.task import MainTaskQueue, TaskStatus, TaskItem
# keep listening and processing until the program is terminated

class VoiceClient:
    """
        ### Cortex Voice Client \n
        Main interface for handling the voice processing pipeline, including STT transcription, interaction with the Cortex Models, and TTS generation. \n
        
        **Key Features:** \n
        - Manages the end-to-end flow of audio input to audio response using `STT Client` and `TTS Client`.
        - Interacts with the `VoiceMainModel` and `CortexMainModel` to generate context-aware responses.
    """
    
    def __init__(self):
        # self.stt_client = STTClient()
        # self.tts_client = TTSClient()
        self.model = VoiceMainModel()
    
    def _get_stream_ready_text(self, buffer: str) -> tuple[str, str]:
        """
        Determines when the accumulated text buffer has reached a point where it can be sent for TTS generation, based on sentence boundaries. \n
        It uses `NLTK's sentence tokenizer` to identify complete sentences in the buffer. \n
        **Input**: \n
        - `buffer`: The current accumulated text buffer from the token stream. \n
        **Returns**: \n
        - A tuple of <ready_text, remaining_buffer> where:
            - `ready_text`: portion of the buffer that is ready to be sent for TTS
            - `remaining_buffer`: part that should be kept for further accumulation.
        """
        
        if not buffer:
            return "", ""
        stripped = buffer.strip()
        if not stripped:
            return "", ""
        if stripped.endswith((".", "!", "?")):
            return stripped, ""
        sentences = sent_tokenize(stripped)
        if len(sentences) <= 1:
            return "", buffer
        return " ".join(sentences[:-1]), sentences[-1]
    
    async def _stream_tts(self, text: str, cancel_event: asyncio.Event | None = None):
        """
        Helper function to stream TTS audio chunks for a given text segment, with support for cancellation. \n
        """
        async for audio_chunk in self.tts_client.get_audio_stream(text):
            if cancel_event and cancel_event.is_set():
                logger.info("Cancelling TTS stream due to interruption")
                return
            yield audio_chunk

    async def listen_and_respond(self, audio_bytes: bytes, cancel_event: asyncio.Event | None = None):
        """
        ### Takes Audio Stream and Responds with Audio Stream \n
        Main function to handle the complete flow of processing incoming audio bytes, transcribing them, generating responses through the model, and streaming back TTS audio chunks. \n
        
        **Input**: \n
        - `audio_bytes`: Raw audio bytes (PCM 16-bit) received from the client. \n
        - `cancel_event`: An optional asyncio.Event that can be set to signal cancellation of the ongoing processing. \n
        
        **Yields**: \n
        - PCM audio chunks as numpy arrays of shape (frame_samples,) and dtype float32
        """
        logger.info("Starting Cortex Main Server...")
            
        text = await self.stt_client.transcribe(audio_bytes)
        if not text:
            return

        print("Transcribed Text:", text)
        pending_text = ""

        # Tokens stream from Voice Main Model
        async for token in iterate_tokens_async(
            generator_callback=self.model.stream_text_tokens,
            cancel_event=cancel_event,
            query=text
        ):
            if cancel_event and cancel_event.is_set():
                logger.info("Cancelling token stream due to interruption")
                return

            pending_text += token
            segment, pending_text = self._get_stream_ready_text(pending_text)

            if segment:
                async for audio_chunk in self._stream_tts(segment, cancel_event):
                    yield audio_chunk

        remaining = pending_text.strip()
        if remaining and not (cancel_event and cancel_event.is_set()):
            async for audio_chunk in self._stream_tts(remaining, cancel_event):
                yield audio_chunk
                
    async def read_and_respond(self, query: str) -> AsyncGenerator[str, None]:
        """
        ### Takes Text as Input and yields Text \n
        Main function to handle the flow of processing an input text query, generating a response through the model, and yielding the response text tokens as they are generated. \n
                
        **Input**: \n
        - `query`: The input text query for which to generate a response. \n
        
        **Yields**: \n
        - The final response text generated by the model after processing the transcribed input.
        """
        logger.info("Starting Cortex Main Server for text response...")

        await MainTaskQueue.add_task(
            payload={"query": query},
            task_name="TextResponseTask"
        )

        immediate_response = "Ok sure, I am looking into it now."
        yield immediate_response

    async def handle_task_queue(self, taskItem: TaskItem, cancel_event: asyncio.Event | None = None) -> AsyncGenerator[bytes, None]:
        print("task name: ", taskItem.task_name)
        print("task status: ", taskItem.status)
        print("task payload: ", taskItem.result)
        async for token in iterate_tokens_async(
            generator_callback=lambda: taskItem.result["response"],
            cancel_event=cancel_event,
        ):
            if cancel_event and cancel_event.is_set():
                logger.info("Cancelling token stream due to interruption")
                return

            pending_text += token
            segment, pending_text = self._get_stream_ready_text(pending_text)
            yield segment

        remaining = pending_text.strip()
        if remaining and not (cancel_event and cancel_event.is_set()):
            yield remaining
        
    async def process_tasks(self):
        """
        ### Background Task Processor \n
        Continuously runs in the background on main thread to process tasks from the `TaskQueue`. \n
        This function can be started as an independent asyncio task when the server starts, allowing it to handle any tasks that are added to the queue. \n
        """
        logger.info("VoiceClient.process_tasks is idle; MainClient.listen_task_queue handles background processing.")
        # Wait for this exact task id to avoid mixing responses across requests.
        while True:
            try:
                taskItem = await MainTaskQueue.wait_completed_task()
                await self.handle_task_queue(taskItem)
            except asyncio.CancelledError:
                raise
            except Exception:
                logger.exception("Unhandled error in VoiceClient.process_tasks")
         