## Set PYTHON_PATH to include workspace root for testing purposes
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))

# env load
from dotenv import load_dotenv
load_dotenv()

# DB Setup
import os
DB_PASSWORD = os.getenv("POSTGRES_PASSWORD")
DB_PORT = os.getenv("POSTGRES_PORT")
DB_USER = os.getenv("POSTGRES_USER")
DB_NAME = os.getenv("POSTGRES_DB")
CORTEX_QUEUE_PORT = os.getenv("CORTEX_QUEUE_PORT")
DB_URL = f"postgresql://{DB_USER}:{DB_PASSWORD}@localhost:{DB_PORT}/{DB_NAME}"
os.environ["DB_URL"] = DB_URL
os.environ["CORTEX_QUEUE_URL"] = f"http://localhost:{CORTEX_QUEUE_PORT}"

# Redis Setup
os.environ["REDIS_HOST"] = os.getenv("REDIS_HOST", "localhost")
os.environ["REDIS_PORT"] = os.getenv("REDIS_PORT", "6379")

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import List, Optional, Dict, Any
from uuid import UUID, uuid4
from datetime import datetime
from dataclasses import asdict

from cortex_queue.dto import TaskItem, TaskStatus
from cortex_cm.pg.enums import TaskOwner
from cortex_core.req import submit_task

"""
## Core Mock Submission Service
This file starts a test server that allows you to submit MOCK completed tasks 
to the Task Queue / Redis DB 2. 

It does NOT invoke any AI workflows. It simply takes a text response from 
your request and formats it into a TaskItem that looks exactly like the output 
of the real core engine.

### Example Request Body for Mock Voice Result
{
    "user_id": "11111111-1111-1111-1111-111111111111",
    "session_id": "22222222-2222-2222-2222-222222222222",
    "query": "Hello Cortex",
    "response": "This is a mock response generated by the test server."
}
"""

app = FastAPI(title="Cortex Core Mock Submission Service")

@app.get("/")
async def root():
    return {"message": "Cortex Core Mock Service is running", "endpoints": ["/health", "/mock_voice_submission", "/mock_event_submission"]}

@app.get("/health")
async def health():
    return {"status": "ok"}

class MockVoiceTaskRequest(BaseModel):
    user_id: UUID
    session_id: UUID
    query: str
    response: str
    emotion: str = "neutral"
    metadata: Optional[Dict[str, Any]] = None

class MockEventTaskRequest(BaseModel):
    message_id: UUID
    name: str
    response: str
    metadata: Optional[Dict[str, Any]] = None

@app.post("/mock_voice_submission")
async def mock_voice_submission(request: MockVoiceTaskRequest):
    """
    Constructs a 'COMPLETED' task item and submits it to the Task Queue.
    """
    task_id = str(uuid4())
    
    # Construct TaskItem exactly as MainClient._handle_voice_client_task would
    task_item = TaskItem(
        task_id=task_id,
        task_name="voice_query_task",
        task_description=f"Mock voice query: {request.query[:30]}...",
        status=TaskStatus.COMPLETED,
        payload={
            "query": request.query,
            "emotion": request.emotion
        },
        metadata={
            "user_id": str(request.user_id),
            "session_id": str(request.session_id),
            "task_owner": TaskOwner.VOICE_CLIENT.value,
            **(request.metadata or {})
        },
        result={
            "response_type": "text_stream",
            "response": request.response
        }
    )
    
    try:
        # Submit to Task Queue (which pushes to Redis DB:2)
        response = await submit_task(task_item=task_item)
        return {
            "status": "success",
            "message": "Mock task submitted to queue",
            "task_id": task_id,
            "queue_response": response
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to hit Task Queue service: {str(e)}")

@app.post("/mock_event_submission")
async def mock_event_submission(request: MockEventTaskRequest):
    """
    Constructs a 'COMPLETED' event task and submits it.
    """
    task_id = str(uuid4())
    
    task_item = TaskItem(
        task_id=task_id,
        task_name="event_tool_task",
        task_description=f"Mock event response",
        status=TaskStatus.COMPLETED,
        payload={
            "name": request.name
        },
        metadata={
            "message_id": str(request.message_id),
            "task_owner": TaskOwner.EVENT_TOOL.value,
            **(request.metadata or {})
        },
        result={
            "response_type": "text_stream",
            "response": request.response
        }
    )
    
    try:
        response = await submit_task(task_item=task_item)
        return {
            "status": "success",
            "message": "Mock event submitted to queue",
            "task_id": task_id,
            "queue_response": response
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to hit Task Queue service: {str(e)}")

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8003)
