from cortex.manager.tools import WebSearchInput
from langchain_core.prompts import PromptTemplate
from pydantic import BaseModel, Field
from typing import Annotated, Literal, Any, Dict, Optional
from langchain_core.output_parsers import StrOutputParser, PydanticOutputParser
from cortex.graph.state import OrchestrationState, PlanEvaluationState, FinalResponseFeedbackState, FinalResponseGenerationState
from cortex.manager.tools import AvailableToolsType

class WebQueryPlanResult(BaseModel):
    query: list[str] = Field(..., description="The list of strings where each string has relevant keywords to search for.")
    context: str = Field(None, description="Direct answer to the user query")
    is_diversified: bool = Field(..., description="Whether the documents from web search are diversified.")

MANAGER_WEB_QUERY_PROMPT = """
# Context: \n
You are a smart query planner for the web search tool. 

# Input Format: \n
1. User Query: Question or information or suggestion from the user that requires web search. \n
2. Instructions by Orchestrator: Additional instructions or constraints provided by the orchestrator to guide the query planning. (can be null) \n

# Task: \n
Based on the user query and the instructions by orchestrator, you have to give: \n
1. A list of relevant queries which can be used for web search. \n
2. A context string which is the direct answer to the user query based on your knowledge. \n
3. A boolean flag indicating whether the documents from web search are diversified. \n

# Instructions - Query: \n
1. Each query should be relevant enough to search for.
2. Strictly follow the orchestrator instructions if provided. If no instructions are provided, generate queries based on the user query alone.
3. Similar Queries must be grouped together while each query in the list should be different from other queries to cover different aspects.
4. Give atleast one query and at max five queries in the output list.

# Instructions - Context: \n
1. Based on the user query and orchestrartor instructions (if any), act as a expert of that field, and provide a paragraph of text that can answer to the user query directly. \n
2. Use professional terminology and a factual tone.
3. Do not use introductory phrases like 'Based on the query...' or 'Here is...'.

# Instructions - Diversification Flag: \n
1. Diversification of documents depends on the type of query. \n
2. Search documents are said to be diversified if semantic overlap between them is low but still each doc is relevant based on query. \n
3. Based on the relevant queries generated by you, have to make a estimation, that after searching on web, the retrieved documents will be diversified or not. \n
4. Do this by understanding the comparison between semantic overlap and relevance of documents. \n
5. For example queries related to news, trips, documentation, suggestions, etc. are diversified but specific queries like 'Tell about planet Earth's dimater', 'What is current exchange rate of USD to INR', etc. are not diversified. \n
6. In case you are not sure, mark it as diversified to give more importance to diversity while retrieval. \n

# Input:
User Query: {user_query}
Instructions by Orchestrator: {orchestrator_instructions}

# Output Format: \n
Follow the below format strictly. Never include any explanations, additional text, python functions, etc in the response. \n
{format_instructions}
"""

TOOL_RESULT_SUMMARIZATION_PROMPT = """
# Input Format: \n
You will be given: \n
1. User Query: Question or information or suggestion from the user. \n
2. Tool Result: To get relevant info, a respective tool is executed and its result is given as input to you. \n
3. Tool Instructions: Additional Instructions specific to the tool. \n

# Input: \n
User Query: {user_query}
Tool Result: {tool_result}

# Tool Specific instructions: \n
{tool_instructions}

# Objective: \n
1. Based on the user query, tool result and specifictool instructions, you have to extract the core facts that answer the user's query. \n
2. Rewrite them as relevant sentences of 10-12 lines (no html tags, json, python functions, etc.). \n
2. Make sure no important information got missed from the tool result while re-organizing facts. \n
3. Your response is later used by the response generator to generate the final response for the user query, so it should be relevant and useful. \n
4. If the tool result is empty, reply with an empty string. Never create any information on your own. \n

# Response Format: \n
String of Relevant sentences, with no extra explanation, text, formatting, python function, etc. Just the concise summary string.
"""

WEB_TOOL_SPECIFIC_INSTRUCTIONS = """
The tool used is Web Search Tool. The tool result will contain concatenated content of multiple web documents. All the Web Documents are relevant. \n
# Instructions:
1. Some of the content might have repeative data, so make sure to not include repeative information. \n
2. Make sure that user query is fully addressed in the summary and no relevant information is missed. \n
"""

TASK_DESCRIPTION_GENERATION_PROMPT = """
# Context: \n
You will be provided following as input: \n
1. User Query: Question or information that user have asked regarding some previous task which have been executed in the past. \n
2. Orchestrator Instructions (can be null or empty): Additional instructions provided by orchestrator to condition the task description generation. \n 

# Objective: \n
1. You are the task description generator for the task retriever tool. \n
2. When task was submitted and executed in the past, it was given a task description which is a concise string describing the task type, purpose, etc. \n
3. Your job is to generate a concise description of the task based on the user query and orchestrator instructions which can be used by the task retriever tool to semantically match and retrieve the same relevant tasks from the past. \n
4. The generated task description should be concise yet informative enough to capture the essence of the task that user is referring to in the query. \n

# Input: \n
User Query: {user_query}
Orchestrator Instructions: {orchestrator_instructions}

# Response Format: \n
String of the task description with no extra explanation, text, formatting, python function, etc. Just the concise task description string.
```your task_description here```
"""

def get_manager_client_prompts(
    type: str,
    tool_type: Optional[str] = None,
):
    if type == "web_query_planning":
        parser = PydanticOutputParser(pydantic_object=WebQueryPlanResult)
        prompt = PromptTemplate(
            template=MANAGER_WEB_QUERY_PROMPT,
            input_variables=[
                "user_query",
                "orchestrator_instructions",
                "format_instructions"
            ],
        )
        return prompt.partial(format_instructions=parser.get_format_instructions()), parser
    elif type == "tool_result_summarization":
        parser = StrOutputParser()
        prompt = PromptTemplate(
            template=TOOL_RESULT_SUMMARIZATION_PROMPT,
            input_variables=[
                "user_query",
                "tool_result",
                "tool_instructions"
            ],
        )
        if not tool_type:
            return prompt.partial(tool_instructions=""), parser
        
        if tool_type == AvailableToolsType.WEB_SEARCH_TOOL.value:
            return prompt.partial(tool_instructions=WEB_TOOL_SPECIFIC_INSTRUCTIONS), parser
        
    elif type == "task_description_generation":
        parser = StrOutputParser()
        prompt = PromptTemplate(
            template=TASK_DESCRIPTION_GENERATION_PROMPT,
            input_variables=[
                "user_query",
                "orchestrator_instructions",
            ],
        )
        return prompt, parser
